# pytest.ini
[pytest]
python_version = 3.12
python_path = /usr/bin/python3.12

# test_file.py
import pytest
from unittest.mock import patch
from unittest.mock import MagicMock
from unittest.mock import PropertyMock
from unittest.mock import Mock
from unittest.mock import ANY
from unittest.mock import call
from unittest.mock import DEFAULT
from unittest.mock import AsyncMock
from unittest.mock import AsyncPropertyMock
from unittest.mock import MagicMock
from unittest.mock import patch
from unittest.mock import PropertyMock
from unittest.mock import Mock
from unittest.mock import ANY
from unittest.mock import call
from unittest.mock import DEFAULT
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import patch
from unittest.mock import